version: 0.2

phases:
  install:
    commands:
      - find $CODEBUILD_SRC_DIR/app-logit -maxdepth 2 -type f -name "package.json" | sort | xargs -I{} dirname {} | xargs -L 1 npm install --prefix
  # pre_build:
  #   commands:
  #     - find $CODEBUILD_SRC_DIR/src -maxdepth 2 -type f -name "package.json" | sort | xargs -I{} dirname {} | xargs -L 1 npm run lint --prefix
  build:
    commands:
      - find $CODEBUILD_SRC_DIR/app-logit -maxdepth 2 -type f -name "package.json" | sort | xargs -I{} dirname {} | xargs -L 1 npm run build --prefix
      - ls
artifacts:
  base-directory: $CODEBUILD_SRC_DIR/app-logit/build/
  files:
    - '**/*'